import { useMemo, useState } from "react";
import { BarChart3, BookOpen, MessageSquare, Search, Sparkles, Users, X, ChevronDown, Quote, CheckCircle2 } from "lucide-react";
import { interviewGuide, transcripts } from "./data";
import "./App.css";

const stats = [["Expert Calls", transcripts.length, "Markets represented"], ["Interview Questions", interviewGuide.length, "Questions in guide"], ["Evidence Segments", transcripts.reduce((n, t) => n + t.segments.length, 0), "Timestamped sources"]];

function App() {
  const [active, setActive] = useState("dashboard"); const [selectedExpert, setSelectedExpert] = useState("all"); const [search, setSearch] = useState(""); const [selectedSegment, setSelectedSegment] = useState(null);
  const visibleExperts = useMemo(() => { const experts = selectedExpert === "all" ? transcripts : transcripts.filter(t => t.id === selectedExpert); if (!search.trim()) return experts; const q = search.toLowerCase(); return experts.map(e => ({ ...e, segments: e.segments.filter(s => s.text.toLowerCase().includes(q) || s.timestamp.includes(q)) })).filter(e => e.segments.length || e.expert.toLowerCase().includes(q) || e.market.toLowerCase().includes(q)); }, [selectedExpert, search]);
  const nav = [["dashboard", "Dashboard", BarChart3], ["guide", "Interview Guide", BookOpen], ["calls", "Expert Calls", Users], ["ask", "Ask AI", MessageSquare]];
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark"><Sparkles size={18}/></div><div><strong>Hasamex AI</strong><span>Expert Intelligence</span></div></div><nav className="navigation">{nav.map(([id,label,Icon])=><button key={id} className={`nav-item ${active===id?"active":""}`} onClick={()=>setActive(id)}><Icon size={17}/>{label}</button>)}</nav><div className="sidebar-footer"><span>AI Transcript Analyzer</span><small>Phase 5 · Interview Guide</small></div></aside><main className="main-content"><header className="page-header"><div><p className="eyebrow">HASAMEX CASE STUDY</p><h1>{active === "dashboard" ? "Expert Call Intelligence" : nav.find(([id])=>id===active)?.[1]}</h1><p className="subtitle">Evidence-first analysis across three expert interviews.</p></div><div className="status-pill"><span/>{transcripts.length} calls loaded</div></header>{active==="dashboard"&&<Dashboard setActive={setActive} setSelectedExpert={setSelectedExpert}/>} {active==="calls"&&<CallsView experts={visibleExperts} selectedExpert={selectedExpert} setSelectedExpert={setSelectedExpert} search={search} setSearch={setSearch} onSelectSegment={setSelectedSegment}/>} {active==="guide"&&<GuideView onSelectSegment={setSelectedSegment}/>} {active==="ask"&&<AskPlaceholder/>}</main>{selectedSegment&&<EvidenceDrawer segment={selectedSegment.segment} expert={selectedSegment.expert} onClose={()=>setSelectedSegment(null)}/>}</div>;
}
function Dashboard({setActive,setSelectedExpert}) { return <><section className="stats-grid">{stats.map(([l,v,d])=><article className="stat-card" key={l}><span>{l}</span><strong>{v}</strong><small>{d}</small></article>)}</section><section className="workspace-grid"><div className="panel"><div className="panel-heading"><div><p className="eyebrow">CASE PACK</p><h2>Expert calls</h2></div><span className="count-badge">3 / 3</span></div><div className="expert-list">{transcripts.map(t=><button key={t.id} className="expert-row" onClick={()=>{setSelectedExpert(t.id);setActive("calls")}}><div className="market-avatar">{t.market.slice(0,2).toUpperCase()}</div><div><strong>{t.expert}</strong><span>{t.role} · {t.market}</span></div><b>View →</b></button>)}</div></div><div className="panel highlight-panel"><p className="eyebrow">INTERVIEW GUIDE</p><h2>Six questions ready for analysis</h2><p>Each question now has an evidence workspace. AI synthesis will be added in the next phase.</p><button className="primary-button" onClick={()=>setActive("guide")}>Open interview guide</button></div></section></>; }
function CallsView({experts,selectedExpert,setSelectedExpert,search,setSearch,onSelectSegment}) { return <section className="content-section"><div className="viewer-toolbar"><select value={selectedExpert} onChange={e=>setSelectedExpert(e.target.value)}><option value="all">All experts</option>{transcripts.map(t=><option key={t.id} value={t.id}>{t.market} · {t.expert}</option>)}</select><div className="search-box"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search transcript evidence..."/><button className="clear-search" onClick={()=>setSearch("")}><X size={13}/></button></div><span className="result-count">{experts.reduce((n,t)=>n+t.segments.length,0)} evidence segments</span></div>{experts.map(t=><article className="transcript-card" key={t.id}><div className="transcript-head"><div><p className="eyebrow">{t.market}</p><h2>{t.expert}</h2><span>{t.role}</span></div><span className="source-badge">{t.segments.length} visible segments</span></div><div className="segment-list">{t.segments.map(s=><button className="segment" key={s.timestamp+s.text} onClick={()=>onSelectSegment({segment:s,expert:t})}><time>{s.timestamp}</time><p>{highlightText(s.text,search)}</p><span className="segment-action">Inspect →</span></button>)}</div></article>)}{!experts.length&&<div className="empty-state"><Search size={20}/><h2>No matching evidence</h2><p>Try another search term.</p></div>}</section>; }
function highlightText(text,q){if(!q.trim())return text;return text.split(new RegExp(`(${escapeRegExp(q)})`,"gi")).map((p,i)=>p.toLowerCase()===q.toLowerCase()?<mark key={i}>{p}</mark>:p)} function escapeRegExp(v){return v.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")}
function GuideView({onSelectSegment}) { const [selectedQuestion,setSelectedQuestion]=useState("q1"); const question=interviewGuide.find(q=>q.id===selectedQuestion); const evidence=questionEvidence(question.id); return <section className="guide-workspace"><div className="guide-sidebar">{interviewGuide.map((item,i)=><button key={item.id} className={`guide-question ${selectedQuestion===item.id?"selected":""}`} onClick={()=>setSelectedQuestion(item.id)}><span>Q{i+1}</span><div><strong>{item.question}</strong><small>{evidence.length} source points</small></div><ChevronDown size={14}/></button>)}</div><div className="answer-workspace"><div className="answer-header"><div><p className="eyebrow">QUESTION {interviewGuide.findIndex(q=>q.id===question.id)+1}</p><h2>{question.question}</h2></div><span className="draft-badge"><Sparkles size={13}/> Evidence ready</span></div><div className="answer-placeholder"><div className="answer-icon"><Sparkles size={22}/></div><div><h3>AI answer synthesis</h3><p>The answer-generation layer will synthesize only the supporting transcript evidence in Phase 6–7. No unsupported conclusion is shown.</p></div></div><div className="evidence-section"><div className="section-heading"><div><p className="eyebrow">SUPPORTING EVIDENCE</p><h3>Source excerpts</h3></div><span>{evidence.length} excerpts</span></div>{evidence.map(({segment,expert})=><button className="evidence-row" key={expert.id+segment.timestamp} onClick={()=>onSelectSegment({segment,expert})}><div className="quote-icon"><Quote size={14}/></div><div className="evidence-copy"><blockquote>“{segment.text}”</blockquote><footer><strong>{expert.expert}</strong><span>{expert.market}</span><time>{segment.timestamp}</time></footer></div><CheckCircle2 size={16} className="verified-icon"/></button>)}</div></div></section>; }
function questionEvidence(id){const keywords={q1:["growth","adoption","expect"],q2:["barrier","cost","funding"],q3:["budget","cost","economic","pay"],q4:["training","surgeon","clinical","outcomes"],q5:["growth","next few","years"],q6:["decision","purchasing"]};const keys=keywords[id]||[];return transcripts.flatMap(expert=>expert.segments.map(segment=>({segment,expert})).filter(({segment})=>keys.some(k=>segment.text.toLowerCase().includes(k))));}
function EvidenceDrawer({segment,expert,onClose}){return <div className="drawer-backdrop" onClick={onClose}><aside className="evidence-drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><p className="eyebrow">SOURCE EVIDENCE</p><h2>Transcript segment</h2></div><button onClick={onClose} className="close-button"><X size={18}/></button></div><div className="evidence-meta"><span>{expert.market}</span><span>{expert.expert}</span><strong>{segment.timestamp}</strong></div><blockquote>“{segment.text}”</blockquote><div className="trace-card"><span>Source trace</span><strong>{expert.expert} · {expert.market} · {segment.timestamp}</strong><small>This exact transcript segment is the source record for the analysis.</small></div></aside></div>}
function AskPlaceholder(){return <section className="ask-card"><div className="ask-icon"><MessageSquare size={25}/></div><p className="eyebrow">CROSS-TRANSCRIPT RESEARCH</p><h2>Ask a question across all expert calls</h2><p>Phase 8 will retrieve evidence across all transcripts before generating an answer.</p><div className="ask-input"><input placeholder="e.g. What are the main barriers to adoption?" disabled/><button disabled>Ask AI</button></div></section>}
export default App;
